AWSTemplateFormatVersion: "2010-09-09"
Description: S3-only static website hosting (public read)

Parameters:
  BucketName:
    Type: String
    Default: ""
    Description: "Optional. If empty, CloudFormation will create a unique bucket name."

Conditions:
  UseCustomBucketName: !Not [!Equals [!Ref BucketName, ""]]

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - UseCustomBucketName
        - !Ref BucketName
        - !Ref "AWS::NoValue"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        # S3 Website Hostingを「公開」で使うため、ブロック系はOFFにする
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForWebsite
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

Outputs:
  BucketName:
    Value: !Ref StaticSiteBucket
    Description: "Upload your site files here (e.g., index.html, assets/, etc.)"

  WebsiteURL:
    Value: !GetAtt StaticSiteBucket.WebsiteURL
    Description: "S3 Website endpoint (HTTP)"
